// ServiceWorker処理：https://developers.google.com/web/fundamentals/primers/service-workers/?hl=ja

// キャッシュ名とキャッシュファイルの指定
const CACHE_NAME = 'aukara-cache-v1';
const urlsToCache = [
    "images/aukaraokecp/btn_coupon_close.png",
    "js/mod.js",
    "images/aukaraokecp/btn_14.png",
    "js/aukaraokecp/jquery-ui.min.js",
    "images/aukaraokecp/favicon.ico",
    "images/aukaraokecp/shop/joysound/logo_01.png",
    "images/icon/button_sidemenu.png",
    "images/aukaraokecp/btn_15.png",
    "css/loading.css",
    "images/aukaraokecp/loading_background.png",
    "images/aukaraokecp/btn_drink.png",
    "images/aukaraokecp/shop/shidax/logo_01.png",
    "images/aukaraokecp/fig_howto_04_600.png",
    "images/aukaraokecp/btn_03c.png",
    "aukaraokecp/coupon/utahiro/index.html",
    "images/aukaraokecp/apple-touch-icon-180x180.png",
    "images/aukaraokecp/apple-touch-icon-152x152.png",
    "404.html",
    "images/aukaraokecp/apple-touch-icon-76x76.png",
    "images/aukaraokecp/btn_03b.png",
    "images/aukaraokecp/au_icon.png",
    "images/aukaraokecp/btn_05.png",
    "images/autuesday/shop/pasela/coupon/b_pasela_20200218_detail.png",
    "js/wrapper.js",
    "aukaraokecp/index.html",
    "js/aukaraokecp/common.js",
    "images/autuesday/shop/borabora/logo_01.png",
    "images/aukaraokecp/img_auPAY_0210_01.gif",
    "images/aukaraokecp/shop/borabora/logo_01.png",
    "images/aukaraokecp/coupon_sumi.png",
    "images/aukaraokecp/fig_howto_02.png",
    "images/aukaraokecp/fig_howto_03.png",
    "images/aukaraokecp/img_main03_mog.png",
    "css/wrapper.css",
    "images/icon/icon_menu_anshin_on.png",
    "images/autuesday/shop/karaokekan/coupon/a_karaokekan_20200218_detail.png",
    "images/autuesday/shop/shidax/btn_01.png",
    "images/autuesday/shop/utahiro/coupon/b_utahiro_20200211_detail.png",
    "images/aukaraokecp/fig_howto_01.png",
    "images/aukaraokecp/modal_btn_close.png",
    "images/icon/button_sidemenu_close.png",
    "images/autuesday/shop/utahiro/coupon/a_utahiro_20200211_detail.png",
    "images/aukaraokecp/btn_11.png",
    "images/aukaraokecp/apple-touch-icon-120x120.png",
    "images/aukaraokecp/tuesday_bullet6.png",
    "images/autuesday/shop/shidax/coupon/b_shidax_20200218_detail.png",
    "js/aukaraokecp/jquery-3.4.1.min.js",
    "images/aukaraokecp/btn_09.png",
    "images/icon/icon_menu_anshin.png",
    "images/icon/icon_menu_app_on.png",
    "images/aukaraokecp/btn_13.png",
    "aukaraokecp/coupon/borabora/index.html",
    "images/aukaraokecp/btn_coupon_space.png",
    "images/icon/icon_menu_app.png",
    "images/loading.gif",
    "images/aukaraokecp/img_main_mog02.jpg",
    "images/aukaraokecp/top_cou_evtue_01.png",
    "images/aukaraokecp/fig_howto_04.png",
    "images/autuesday/shop/utahiro/coupon/b_utahiro_20190430_detail.png",
    "images/aukaraokecp/apple-touch-icon.png",
    "images/aukaraokecp/btn_coupon_open.png",
    "images/aukaraokecp/img_auPAY_2001_560x220.jpg",
    "images/aukaraokecp/shop/utahiro/logo_01.png",
    "index.html",
    "images/aukaraokecp/top_cou_info_02.png",
    "images/aukaraokecp/img_main02.png",
    "images/aukaraokecp/img_header01_mog.png",
    "images/aukaraokecp/img_main_mog02_600.png",
    "images/aukaraokecp/tuesday_cur.png",
    "js/aukaraokecp/jquery.colorbox.js",
    "images/icon/search_bar_button.png",
    "images/aukaraokecp/btn_24.png",
    "images/icon/icon_menu_point.png",
    "js/aukaraokecp/jquery.easing.js",
    "images/icon/icon_menu_point_on.png",
    "images/aukaraokecp/btn_02.png",
    "images/aukaraokecp/coupon-bottom.png",
    "images/aukaraokecp/btn_04.png",
    "images/aukaraokecp/loading.gif",
    "images/aukaraokecp/btn_20.png",
    "images/aukaraokecp/top_cou_info_01.png",
    "js/aukaraokecp/jquery.layerBoard.js",
    "js/aukaraokecp/jquery.switchHat.js",
    "images/autuesday/shop/utahiro/coupon/a_utahiro_20190430_detail.png",
    "images/autuesday/shop/joysound/btn_01.png",
    "images/autuesday/shop/shidax/logo_01.png",
    "images/aukaraokecp/coupon-top.png",
    "images/aukaraokecp/btn_21.png",
    "images/aukaraokecp/btn_07.png",
    "images/aukaraokecp/controls.png",
    "aukaraokecp/coupon/pasela/index.html",
    "images/autuesday/shop/joysound/coupon/a_joysound_20200218_detail.png",
    "images/aukaraokecp/btn_16.png",
    "images/autuesday/shop/pasela/btn_01.png",
    "images/aukaraokecp/ico_close.gif",
    "images/aukaraokecp/btn_01.png",
    "images/autuesday/shop/karaokekan/coupon/b_karaokekan_20200218_detail.png",
    "images/autuesday/shop/karaokekan/logo_01.png",
    "css/wrapper_base.css",
    "images/icon/back_bar_button.png",
    "images/aukaraokecp/btn_03a.png",
    "images/aukaraokecp/shop/pasela/logo_01.png",
    "images/autuesday/shop/pasela/coupon/a_pasela_20200218_detail.png",
    "manifest.json",
    "images/aukaraokecp/shop_title.png",
    "css/aukaraokecp/mogimae.css",
    "images/aukaraokecp/shop/karaokekan/logo_01.png",
    "js/aukaraokecp/scroll.js",
    "images/aukaraokecp/btn_18.png",
    "images/aukaraokecp/btn_19.png",
    "images/aukaraokecp/btn_22.png",
    "images/icon/mypage_bar_button.png",
    "css/aukaraokecp/sp.css",
    "images/autuesday/shop/utahiro/logo_01.png",
    "images/aukaraokecp/btn_06.png",
    "images/aukaraokecp/shop_btn.png",
    "images/autuesday/shop/borabora/btn_01.png",
    "images/icon/icon_menu_home.png",
    "//www.googletagmanager.com/gtm.js?id=GTM-K25DZQH",
    "images/autuesday/shop/karaokekan/btn_01.png",
    "css/aukaraokecp/print.css",
    "css/aukaraokecp/default.css",
    "images/autuesday/shop/borabora/coupon/b_borabora_20200218_detail.png",
    "images/autuesday/shop/shidax/coupon/a_shidax_20200218_detail.png",
    "images/icon/icon_menu_tokuten.png",
    "images/aukaraokecp/btn_17.png",
    "images/aukaraokecp/btn_23.png",
    "images/autuesday/shop/borabora/coupon/a_borabora_20200218_detail.png",
    "images/autuesday/shop/utahiro/btn_01.png",
    "images/aukaraokecp/coupon-title.png",
    "images/aukaraokecp/img_auPAY_2010_btn.png",
    "images/autuesday/shop/pasela/logo_01.png",
    "images/icon/icon_menu_home_on.png",
    "images/aukaraokecp/top_cou_info_01_600.png",
    "images/autuesday/shop/joysound/logo_01.png",
    "css/aukaraokecp/colorbox.css",
    "images/aukaraokecp/btn_08.png",
    "images/aukaraokecp/coupon_title.png",
    "images/aukaraokecp/img_main02_600.png",
    "images/aukaraokecp/img_auPAY_0210_02.png",
    "images/aukaraokecp/btn_12.png",
    "images/aukaraokecp/ico_open.gif",
    "images/icon/icon_menu_tokuten_on.png",
    "images/autuesday/shop/joysound/coupon/b_joysound_20200218_detail.png",
    "js/aukaraokecp/jquery.cookie.js",
    "images/aukaraokecp/btn_10.png",
    "js/aukaraokecp/stamping.js"
];

// インストール処理
self.addEventListener('install', e => {
    e.waitUntil(
        caches
        .open(CACHE_NAME)
        .then(cache => {
            return cache.addAll(urlsToCache);
        })
        .then(() => self.skipWaiting())
    );
});

// リソースフェッチ時のキャッシュロード処理
self.addEventListener('fetch', e => {
    // 外部リソース取得時
    console.log('fetch', e.request.url);
    e.respondWith(
        caches.match(e.request, {
            ignoreSearch: true
        })
        .then(response => {
            return response || fetch(e.request);
        })
    );
});